services:
  keycloak:
    container_name: keycloak-app
    image: quay.io/keycloak/keycloak:26.0.2
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    networks:
      - ms-network
      
  ecommerce:
    container_name: ecommerce
    build:
      context: ./store
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - keycloak
    networks:
      - ms-network

networks:
  ms-network:
    driver: bridge
