version: '3.8'

services:
  keycloak:
    container_name: keycloak-app
    image: quay.io/keycloak/keycloak:26.0.2
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev